apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-api-internal-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: korifi-api-svc.{{ .Release.Namespace }}.svc.cluster.local
  dnsNames:
  - korifi-api-svc.{{ .Release.Namespace }}.svc
  - korifi-api-svc.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: korifi-api-internal-cert
  subject:
    organizations:
    - korifi
  usages:
  - server auth
