{{- if .Values.api.expose }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: korifi-api
  name: korifi-api-proxy
  namespace: {{ .Release.Namespace }}
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: korifi-api-svc
      port: 443
      validation:
        caSecret: korifi-api-internal-cert
        subjectName: korifi-api-svc.{{ .Release.Namespace }}.svc.cluster.local
    timeoutPolicy:
      response: 5m
  virtualhost:
    fqdn: {{ .Values.api.apiServer.url }}
    tls:
      secretName: korifi-api-ingress-cert
{{- end }}
