kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: sidecar-gateway
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    group: projectcontour.io
    kind: ContourDeployment
    namespace: projectcontour
    name: contour-params
