apiVersion: v1
kind: Service
metadata:
  name: korifi-controllers-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: korifi-controllers

{{- if .Values.debug }}
---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-debug-port
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: debug-30051
      nodePort: 30051
      port: 30051
      protocol: TCP
      targetPort: 40000
  selector:
    app: korifi-controllers
  type: NodePort
{{- end }}
