---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korifi-kpack-build-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  - serviceaccounts/status
  verbs:
  - get
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - builderinfos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - builderinfos/status
  verbs:
  - get
  - patch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - buildworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - buildworkloads/status
  verbs:
  - get
  - patch
- apiGroups:
  - kpack.io
  resources:
  - builders
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kpack.io
  resources:
  - builds
  verbs:
  - deletecollection
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kpack.io
  resources:
  - builds/finalizers
  verbs:
  - get
  - patch
- apiGroups:
  - kpack.io
  resources:
  - builds/status
  verbs:
  - get
  - patch
- apiGroups:
  - kpack.io
  resources:
  - clusterbuilders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kpack.io
  resources:
  - clusterbuilders/status
  verbs:
  - get
- apiGroups:
  - kpack.io
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kpack.io
  resources:
  - images/status
  verbs:
  - get
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - list
  - watch
