apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: my-crd.cloudfoundry.org
spec:
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: MyCRDs
    singular: MyCRD
    kind: MyCRD
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        my-example-secret-ref:
          type: string
        spec:
          type: object
          properties:
            my-example-nested-configmap-ref:
              type: string
            selector:
              type: object
            template:
              type: object
