---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: cf-for-k8s-develop-ci
  - name: pool-repo

outputs:
  - name: pool-repo

params:
  STALE_AFTER_DAYS: "5"

run:
  path: cf-for-k8s-develop-ci/ci/tasks/schedule-stale-envs-for-deletion/task
