apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-kpaas-user-admin
  namespace: kpaas
  labels:
    cloudfoundry.org/role-guid: my-kpaas-user-admin-guid
  annotations:
    cloudfoundry.org/propagate-cf-role: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korifi-controllers-admin
subjects:
  - kind: ServiceAccount
    name: my-service-account
    namespace: my-service-account-namespace
