---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
- name: runtime-ci
- name: env-metadata

run:
  path: /bin/bash
  args:
  - -euc
  - |
    cf_api_url="api.$(cat env-metadata/dns-domain.txt)"

    go run runtime-ci/tasks/ensure-api-healthy/main.go "https://${cf_api_url}/v3/info"
