apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: {{ .Values.rootNamespace }}
  annotations:
    cloudfoundry.org/propagate-service-account: "true"
    cloudfoundry.org/propagate-deletion: "false"
    {{- if .Values.eksContainerRegistryRoleARN }}
    eks.amazonaws.com/role-arn: {{ .Values.eksContainerRegistryRoleARN }}
    {{- end }}
{{- if not .Values.eksContainerRegistryRoleARN }}
{{- if .Values.containerRegistrySecrets }}
secrets:
{{- range .Values.containerRegistrySecrets }}
- name: {{ . | quote }}
{{- end }}
imagePullSecrets:
{{- range .Values.containerRegistrySecrets }}
- name: {{ . | quote }}
{{- end }}
{{- else }}
secrets:
- name: {{ .Values.containerRegistrySecret | quote }}
imagePullSecrets:
- name: {{ .Values.containerRegistrySecret | quote }}
{{- end }}
{{- end }}
