---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
metadata:
  name: kapp-istio-gateway-rules

templateRules:
- resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: Secret}
  affectedResources:
    objectReferences:
    - path: [spec, servers, {allIndexes: true}, tls]
      resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: networking.istio.io/v1alpha3, kind: Gateway}
      nameKey: credentialName
