---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korifi-statefulset-runner-appworkload-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/finalizers
  verbs:
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - appworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - appworkloads/status
  verbs:
  - get
  - patch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - runnerinfos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - runnerinfos/status
  verbs:
  - get
  - patch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - deletecollection
  - patch
