# The CF Root Namespace User
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korifi-controllers-root-namespace-user
rules:
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfdomains
  verbs:
  - get
  - list

- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cforgs
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - builderinfos
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - runnerinfos
  verbs:
  - get
  - list
  - watch
