# The CF Space Developer Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korifi-controllers-space-developer
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - patch
  - get
  - create

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list

- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get

- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get

- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfapps
  verbs:
  - get
  - create
  - patch
  - delete
  - list
  - watch

- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - appworkloads
  verbs:
  - list

- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfprocesses
  verbs:
  - create
  - get
  - list
  - patch

- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfpackages
  verbs:
  - get
  - list
  - create
  - patch
  - watch

- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfbuilds
  verbs:
  - get
  - list
  - create
  - patch

- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfserviceinstances
  verbs:
  - get
  - list
  - create
  - patch
  - delete
  - watch

- apiGroups:
    - korifi.cloudfoundry.org
  resources:
    - cfservicebindings
  verbs:
    - get
    - list
    - create
    - delete
    - watch
    - patch

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list

- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfroutes
  verbs:
  - get
  - create
  - delete
  - list
  - patch
  - update

- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cftasks
  verbs:
  - get
  - create
  - delete
  - list
  - patch
  - watch
