---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/relint-base

inputs:
- name: cf-for-k8s-ci

run:
  path: cf-for-k8s-ci/ci/tasks/verify-every-task-is-used-in-a-pipeline/task.sh
