---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korifi-job-task-runner-taskworkload-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - taskworkloads
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - taskworkloads/finalizers
  verbs:
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - taskworkloads/status
  verbs:
  - get
  - patch
