#@ load("@ytt:data","data")
#@ load("@ytt:base64","base64")
#@ if data.values.ccdb.ca_cert:
---
apiVersion: v1
kind: Secret
metadata:
  name: database-ca-cert
  namespace: #@ data.values.system_namespace
type: Opaque
data:
  ca.crt: #@ base64.encode(data.values.ccdb.ca_cert)
#@ end
