---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
- name: cf-for-k8s-ci
- name: cf-for-k8s-last-release
- name: cf-for-k8s-rc
- name: cf-for-k8s-rc-version

params:
  GITHUB_API_USER:
  GITHUB_API_TOKEN:

run:
  path: cf-for-k8s-ci/ci/tasks/check-values-interface/task.sh
