---
# Defines the CF App
apiVersion: korifi.cloudfoundry.org/v1alpha1
kind: CFApp
metadata: #korifi.cloudfoundry.org/* labels are managed by a mutating webhook
  name: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
  namespace: cf
spec:
  displayName: my-app # validated to be unique per namespace by validating webhook
  currentDropletRef: # starts empty and is filled by CF Shim PATCH endpoint /v3/apps/:guid/current_droplet
    name: 1591ee05-e208-4cf3-a662-1c2da42f20a7
  desiredState: STARTED
  lifecycle:
    # We use this info to make a Builder per app: https://github.com/cloudfoundry/cloud_controller_ng/blob/a698d407d9f11263152cfdc4317f4786567bb16f/lib/cloud_controller/kpack/stager.rb#L153
    type: buildpack
    data:
      buildpacks: [ ]
      stack: cflinuxfs3
