apiVersion: korifi.cloudfoundry.org/v1alpha1
kind: CFRoute
metadata:
  name: 84afc0f2-3dc2-4709-9fc8-8340be584a43
  namespace: cf
spec:
  host: my-host
  path: /
  protocol: http
  domainRef:
    name: 5b5032ab-7fc8-4da5-b853-821fd1879201
    namespace: cf
  # This array of destinations starts empty and is filled by CF Shim endpoints for /v3/routes/:guid/destinations
  destinations:
    - guid: 8ad77ef4-53d5-117a-b640-0ae227a13f35
      port: 8080
      appRef:
        name: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
      processType: web
      protocol: http1
