apiVersion: korifi.cloudfoundry.org/v1alpha1
kind: CFServiceInstance
metadata:
  name: 7e0dec79-2f4e-43ee-a682-3c3f4b8e7fd1 # service instance guid
  namespace: cf
  labels:
    servicebinding.io/provisioned-service: "true"
spec:
  displayName: my-upsi # service instance name requested by dev
  secretName: cf-service-credentials-7e0dec79-2f4e-43ee-a682-3c3f4b8e7fd1
  type: user-provided
  tags:
    - list of
    - arbitrary strings
    - that are included in `VCAP_SERVICES` env
