# The CF Organization Manager Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korifi-controllers-organization-manager
rules:
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cforgs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfspaces
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - builderinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - runnerinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - delete
